title: Syed Ahmed Ullah # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer
  <br><br>
  Ahmedullah Syed is a software engineer and a passionate mobile application
developer, with a track record of creating and implementing successful android
application. Keep up-to-date with constantly evolving technologies, and work closely
with clients to create innovative, effective and creative mobile applications.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
